TARGET_HAS_THIRD_PARTY_APPS := true
BOARD_USES_TSLIB := false
#BOARD_WPA_SUPPLICANT_DRIVER :=
#BOARD_GPU_DRIVERS := vmwgfx
BOARD_USES_KBDSENSOR := true
BOARD_USES_KBDSENSOR_ROTKEY1 := true

include $(GENERIC_X86_CONFIG_MK)

BOARD_KERNEL_CMDLINE += SDCARD=sda
